_wandb:
    value:
        cli_version: 0.27.0
        e:
            k7xq31gxaah8zkh2oibkcpptiomsjtpv:
                codePath: scripts/upload_metrics_to_wandb.py
                codePathLocal: scripts/upload_metrics_to_wandb.py
                email: beomjinkim2000@gmail.com
                executable: /Users/apple/Documents/GitHub/Code_IT_Team_1_FirstProject/.venv/bin/python
                git:
                    commit: 8a239b4b396c7e1737ded37a3ddd1755ef32d9e3
                    remote: https://github.com/beomjinkim2000/Code_IT_Team_1_FirstProject.git
                host: appleui-MacBookAir.local
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/apple/Documents/GitHub/Code_IT_Team_1_FirstProject/scripts/upload_metrics_to_wandb.py
                python: CPython 3.14.0
                root: /Users/apple/Documents/GitHub/Code_IT_Team_1_FirstProject
                startedAt: "2026-06-02T01:07:06.377546Z"
                writerId: k7xq31gxaah8zkh2oibkcpptiomsjtpv
        m: []
        python_version: 3.14.0
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.14.0
            "5": 0.27.0
            "8":
                - 2
            "10":
                - 20
            "12": 0.27.0
            "13": darwin-arm64
batch_size:
    value: 8
epochs:
    value: 200
model:
    value: yolov8x
source:
    value: gdrive-historical
